Repository wecode-bootcamp-korea/18-1st-KakaoVillains-backend, pull requests merged in 2021-03, with the labels that each got.

#1 models.py 코멘트사항 수정완료
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/0001_initial.py
  account/migrations/0002_auto_20210318_0530.py
  account/migrations/0003_user_liked_feed.py
  account/migrations/0004_auto_20210318_0729.py
  account/migrations/__init__.py
  account/models.py
  account/tests.py
  account/urls.py
  account/views.py
  feed/__init__.py
  feed/admin.py
  feed/apps.py
  feed/migrations/0001_initial.py
  feed/migrations/0002_feed_product.py
  feed/migrations/0003_auto_20210318_0729.py
  feed/migrations/__init__.py
  feed/models.py
  feed/tests.py
  feed/views.py
  kakaovillains/settings.py
  kakaovillains/urls.py
  kakaovillains_20210316_32_16.png
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_character_product.py
  product/migrations/0003_product_updated_at.py
  product/migrations/0004_auto_20210318_0729.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  purchase/__init__.py
  purchase/admin.py
  purchase/apps.py
  purchase/migrations/0001_initial.py
  purchase/migrations/0002_transaction_product.py
  purchase/migrations/0003_auto_20210318_0547.py
  purchase/migrations/0004_auto_20210318_0729.py
  purchase/migrations/0005_auto_20210318_0731.py
  purchase/migrations/__init__.py
  purchase/models.py
  purchase/tests.py
  purchase/views.py
  utils/decorators.py
Labels: Status: Accepted

#2 sign in capture added
  account/views.py
  aquery.png
  sign_in_success.png
Labels: Status: Accepted

#6 Add: utils.decorator indicator 함수 생성
  utils/decorators.py
Labels: Status: Accepted

#7 [긴급] 데코레이터 수정하였습니다. 머지시켜주세요
  utils/decorators.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#8 [긴급] Category 관련 models.py 수정 했습니다.
  product/migrations/0005_auto_20210324_1158.py
  product/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#5 [이왕록]Feature/product 수정 완료
  account/views.py
  feed/migrations/0004_auto_20210321_0857.py
  feed/models.py
  kakaovillains/urls.py
  product/urls.py
  product/views.py
  purchase/views.py
Labels: Status: Accepted

#9 [긴급]requirements sync
  requirements.txt
Labels: Status: 도움 요청, Status: 리뷰 요청

#4 [허정원]Feature/feed 피드 관련 기능 수정
  .vscode/settings.json
  account/views.py
  feed/migrations/0004_auto_20210319_0058.py
  feed/models.py
  feed/urls.py
  feed/views.py
  kakaovillains/urls.py
  product/models.py
  utils/decorators.py
Labels: Status: 리뷰 요청
